### ISSUE TITLE
한나눔 에러인가요?

### ISSUE THREAD

**Issue by leesm0218** [nearbydelta/KoalaNLP#16]
간단한 번역기. 복잡한 파서 <- 를 분석하라고 했더니 xpn 에러가 떠서 올립니다.

[main] INFO kr.bydelta.koala.traits.CanExtractResource - Extracting dictionary resources to C:\Users\leesm\AppData\Local\Temp\koalanlp-hannanum.
[main] INFO kr.bydelta.koala.traits.CanExtractResource - Extraction finished.
Input a sentence >> 간단한 번역기. 복잡한 파서
FILE: C:\Users\leesm\AppData\Local\Temp\koalanlp-hannanum\data/kE/dic_analyzed.txt
Exception in thread "main" java.util.NoSuchElementException: No value found for 'XPN'
	at scala.Enumeration.$anonfun$withName$2(Enumeration.scala:125)
......

아래는 사용한 소스코드입니다...만 올려주셨던 예제와 똑같습니다.

import kr.bydelta.koala.POS;
import kr.bydelta.koala.POS$;
import kr.bydelta.koala.data.Sentence;
import kr.bydelta.koala.hnn.JavaDictionary;//한나눔
import kr.bydelta.koala.hnn.Parser;             //한나눔
import kr.bydelta.koala.hnn.Tagger;            //한나눔

import java.util.LinkedList;
import java.util.List;
import java.util.Scanner;

@SuppressWarnings("WeakerAccess")
public class App {
    public static void main(String[] args) {
        /* 사용자정의사전 사용법 */
        // 1. 형태소 기본형 추가.
        List<String> list = new LinkedList<>();
        list.add("설빙");
        list.add("구글하");

        // 2. 기본형별 품사 지정.
        List<POS$.Value> pos = new LinkedList<>();
        pos.add(POS.NNG());
        pos.add(POS.VV());

        // 3. JavaDictionary에 추가.
        JavaDictionary.addUserDictionary(list, pos);

        /* Tagger & Parser 사용법 */
        Tagger tagger = new Tagger();
        Parser parser = new Parser();
        String line;
        Scanner scan = new Scanner(System.in);

        do {
            System.out.print("Input a sentence >> ");
            line = scan.nextLine();
            if (!line.isEmpty()) {
                // 문단 단위를 Tagging하는 경우:
                List<Sentence> paragraph = tagger.jTagParagraph(line);
                // 1개 문장인 경우는, 아래와 같습니다.
                // Sentence sent = tagger.tagSentence(line);
                // 문장이 1개라면,바로 의존관계분석을 할 수도 있습니다.
                // Sentence sent = parser.parse(line);

                for (Sentence sent : paragraph) {
                    // 아래와 같이, 의존관계분석을 진행합니다.
                    // Sentence 객체를 넣었으므로, 해당 객체에 변경사항이 기록됩니다.
                    parser.parse(sent);

                    System.out.println(sent.singleLineString());
                    System.out.println();
                }
            }
        } while (!line.isEmpty());
    }
}

**Comment by nearbydelta** [comment]
혹시 stack trace 부분을 전부 올려주실 수 있으실까요? 버그인 것 같습니다.

**Comment by nearbydelta** [comment]
한나눔 코드 상에서 사전에서 사용하지 않는 XPN(체언접두사)을 생성하는 부분이 있었습니다.
아마 구문 분석 과정에서 XP(접두사)를 의존 라이브러리가 인식하는 XPN(체언접두사)으로 변경하고 복원하지 않은 것 같습니다.
코드는 업데이트 되었고, Maven Central에 반영되려면 3~5시간 정도 걸릴 것 같습니다.

**Comment by nearbydelta** [comment]
다량의 테스트 결과 한나눔 파서 결과물이 한나눔 태그셋을 따르지 않는 점이 확인되었습니다. 수정중입니다.

**Comment by nearbydelta** [comment]
1.5.2 버전에서 문제를 해결하여 배포하였습니다. 감사합니다.
