### ISSUE TITLE
파서,태그,의존관계 질문.

### ISSUE THREAD

**Issue by leesm0218** [nearbydelta/KoalaNLP#17]
import kr.bydelta.koala.hnn.Parser;
import kr.bydelta.koala.hnn.Tagger;

public class hnn_r {
    public static void main(String[] args) {
        //Tagger & Parser 사용법
        Tagger tagger = new Tagger();
        Parser parser = new Parser();
        String line = "철수는 손을 베다";
        
        System.out.println(tagger.tagSentence(line));
        System.out.println(parser.parse(line));
    }
}

결과는 다음과 같습니다.

철수는 손을 베다
철수는	= 철수/NNG(ncpa)는/JX(jxc)
손을	= 손/NNG(ncn)을/JKO(jco)
베다	= 베/NNG(ncn)이/VCP(jp)다/EF(ef)
철수는  손을  베이다 
철수는 	= 철수/NNG(NNG)는/JX(JX)
손을 	= 손/NNG(NNG)을/JKO(JKO)
베이다 	= 베/NNG(NNG)이/VCP(VCP)다/EC(EC)
	의존관계:--[Subject]--> 0 --[Object]--> 1[ROOT]

뜬금없이 "베이다" 가 나오고 주어,목적어 다음에 root 가 나오는데 root 의 의미를 모르겠습니다.
숫자의 의미도 잘 이해가 안가서 같이 질문드립니다

**Comment by nearbydelta** [comment]
> 철수는 손을 베다
> 철수는	= 철수/NNG(ncpa)는/JX(jxc)
> 손을	= 손/NNG(ncn)을/JKO(jco)
> 베다	= 베/NNG(ncn)이/VCP(jp)다/EF(ef)
여기까지가 품사 분석의 결과입니다. 한나눔 분석기가 "베다"를 "베+-이-+-다"로 분석한 것 같습니다.
이 분석 결과의 문제는 한나눔 분석기 자체의 문제입니다.

KoalaNLP는 여러 분석기 라이브러리를 변경 없이 모아서 통합 인터페이스를 제공하고 있습니다.
때문에 각 분석기의 오류는 각 분석기 개발팀에 문의하셔야 하나, 한나눔의 경우 현재 유지관리가 되지 않고 있는 것으로 알고 있습니다.

* 참고: 기계학습으로 학습한 결과를 활용하다보니 오류가 있을 수 있고, 완벽하게 분석하는 분석기는 현재 없다는 점을 참고해주세요.

> 철수는 손을 베이다
> 철수는 = 철수/NNG(NNG)는/JX(JX)
> 손을 = 손/NNG(NNG)을/JKO(JKO)
> 베이다 = 베/NNG(NNG)이/VCP(VCP)다/EC(EC)
> 의존관계:--[Subject]--> 0 --[Object]--> 1[ROOT]
이 부분이 의존구문분석의 결과입니다.
의존관계가 정상적으로 표시되지 않는 것 같습니다.
이 부분은 KoalaNLP의 통합 과정에 문제가 생긴 듯 하니, 확인해보겠습니다.
제가 당장은 해결할 수 없어서 시일이 좀 걸릴 것 같습니다. 진행에 참고하시면 좋을 것 같습니다.
