### ISSUE TITLE
의존관계 트리 질문.

### ISSUE THREAD

**Issue by leesm0218** [nearbydelta/KoalaNLP#18]
소스는 아래와 같습니다.
public class hnn_r {
    public static void main(String[] args) {
        //Tagger & Parser 사용법
        Tagger tagger = new Tagger();
        Parser parser = new Parser();
        String line = "멋진 나는 밥만있어도 함께 먹는다";
        Sentence sent = parser.parse(line);
        
        System.out.println(sent.treeString());
    }
}

결과문은 아래와 같습니다.
+Undefined : 먹/VV+는다/EF ... ROOT
 +Subject : 나/NP+는/JX ... SBJ
 +Object : 밥만있어/NNG+도/JX ... OBJ
 +Adjunct : 함께/MAG ... ADV
  +Modifier : 멋지/VA+ㄴ/ETM ... MOD

  +Modifier : 멋지/VA+ㄴ/ETM ... MOD<- 가 어느 노드의 하위 노드인지 구분하는법을 몰라서 질문드립니다.

또한

"멋진 나는 저녁이 밥일지라도 함께 먹는다"의 결과는
+Undefined : 먹/VV+는다/EF ... ROOT
 +Subject : 나/NP+는/JX ... SBJ
 +Complement : ㄹ지/VV+라도/EC ... CMP
 +Adjunct : 함께/MAG ... ADV
  +Modifier : 멋지/VA+ㄴ/ETM ... MOD
  +Subject : 저녁/NNG+이/JKS ... SBJ
  +Subject : 밥/NNG+이/JKS ... SBJ

로 나왔습니다. 저녁밥과 멋진이 함께 있어서 어느 명사의 하위 노드인지 트리만 봐서는 잘 모르겠습니다.

**Comment by nearbydelta** [comment]
> +Undefined : 먹/VV+는다/EF ... ROOT
> +Subject : 나/NP+는/JX ... SBJ
> +Object : 밥만있어/NNG+도/JX ... OBJ
> +Adjunct : 함께/MAG ... ADV
> +Modifier : 멋지/VA+ㄴ/ETM ... MOD

아마 println으로 화면에 출력하셨다면 들여쓰기가 되어있을 것입니다.
붙여넣기 과정에서 띄어쓰기가 없어졌네요.. 폴더 구조 표시하듯 트리 구조가 표시되니 참고하시면 됩니다.

참고로, toString은 데모를 위한 것이고, sent 내에 root 노드부터 순회할 수 있도록 여러 메소드가 있으니 이를 활용하셔서 트리 구조를 순회하시는 것이 좋겠습니다. 자세한 사항은 (Javadoc의 Sentence 부분)[http://nearbydelta.github.io/KoalaNLP/api/java/kr/bydelta/koala/data/Sentence.html]이나, Repository main의 README 부분에 서술된 내용을 참고하시면 될 것 같습니다.

**Comment by leesm0218** [comment]
아...제대로 확인도 안하고 질문드려서 죄송합니다.

띄어쓰기를 - 로 대체했을떄 이렇게 나옵니다.

+Undefined : 먹/VV+는다/EF ... ROOT
 +Subject : 나/NP+는/JX ... SBJ
 +Complement : ㄹ지/VV+라도/EC ... CMP
 +Adjunct : 함께/MAG ... ADV
  +Modifier : 멋지/VA+ㄴ/ETM ... MOD
  +Subject : 저녁/NNG+이/JKS ... SBJ
  +Subject : 고기/NNG+이/JKS ... SBJ

(-+Adjunct : 함께/MAG ... ADV) 노드에 의존하는 노드가 3개 있는건가요?

**Comment by nearbydelta** [comment]
그 경우에,
Root -> 먹+는다
먹는다 -> 나+는 : 주어
먹는다 -> (이)ㄹ지+라도 : 보어
먹는다 -> 함께 : 부사어
함께 -> 멋지+ㄴ : 수식어
함께 -> 저녁+이 : 주어
함께 -> 고기+이 : 주어 

이렇게 해석하시면 됩니다.
그러므로, 결과 상으로는 '함께' 노드에 의존하는 하위노드가 3개인 게 맞습니다.

**Comment by leesm0218** [comment]
아..."멋진" 이 "나" 의 하위노드가 아닌건가요? 한국인이지만 한국어 문법 어렵네요...

**Comment by nearbydelta** [comment]
분석 결과를 100% 믿지 않으시는 게 좋습니다.
1. 기계 학습으로 된 분석 결과들이라 틀릴 가능성이 상존하는데다가
1. 어순에 따라서 한국어는 분석 결과가 많이 달라지거든요..

아마 원문이 "멋진 나는 저녁이 고기일지라도 함께 먹는다"였던 것 같은데요.

제가 한나눔을 개발한 건 아니지만, 일반적인 자연어처리 기술을 생각하면,
작성하신 문장이 주어가 두개인 것 처럼 보이는 문장이라(`나는`, `저녁이`)
분석에 오류가 좀 있었을지도 모르겠습니다.

아마도 "저녁이 고기일지라도 멋진 나는 함께 먹는다"는 또 다른 결과를 줄 것 같습니다.

그리고 참고로 꼬꼬마 의존관계 분석은 아마 다음과 같이 결과를 줄 것 같습니다. 
* 꼬꼬마는 [웹 테스트 환경](http://kkma.snu.ac.kr/concordancer)이 있습니다.

> 먹는다
>> 함께
>> 고기일지라도
>>> 저녁이
>>> 나는
>>>> 멋진

**Comment by leesm0218** [comment]
Sentence.treeString 출력
+Conjunctive : 먹/VV+는/EP+다/EF ... 연결
-+Conjunctive : 고기/NNG+이/VCP+ㄹ지라도/EC ... 대등 연결
-+Modifier : 함께/MAG ... 수식
--+Subject : 나/NP+는/JX ... 주어
--+Subject : 저녁/NNG+이/JKS ... 주어
--+Modifier : 멋지/VA+ㄴ/ETM ... 수식

꼬꼬마쪽은 어느쪽이 주된 주어인지 잡아주질 못하네요... 질문에 답변해주셔서 감사합니다.
