### ISSUE TITLE
Spark에서 사용을 하기위한 방안 문의 (scala 2.12 이슈)

### ISSUE THREAD

**Issue by bongki** [nearbydelta/KoalaNLP#19]
### 기초정보
- KoalaNLP 버전은요? (Version of KoalaNLP)? 
  - g : kr.bydelta
  - a : koalanlp-twitter_2.11
  - v : 1.5.2
- 어떤 프로그래밍 언어에서 문제가 생겼습니까? (Language Type)? ([]안에 x표하여 표기해주세요; Please mark one with [x] symbol)
  - [ ] Java
  - [x] Scala
  - [ ] Other
- 문제의 유형은 어떤 것인가요? (Type of this issue)?
  - [ ] 버그리포트. Bug report
  - [ ] 개선점제안. Idea/Suggestion for a improvement
  - [x] 사용법질문. Question about using KoalaNLP
  - [ ] 기타. Other

### 재연을 위한 정보
- KoalaNLP를 사용한 코드 부분을 보여주세요. (Please show your code snippet which uses KoalaNLP.)
```scala
import kr.bydelta.koala.twt.SentenceSplitter

def extractWord(text: String): List[String] = {
  val sentenceSplitter = new SentenceSplitter
  sentenceSplitter.sentences(text).toList
}
```

### 본문
Spark(2.2.0)을 사용하여 단어 목록을 추출하고자 하는 과정에서 scala 2.12 버전에 대한 이슈가 발생하였습니다.
```
java.langNosuchMethroError: scala.Product$init ...
```
의존성을 체크해볼 결과 koalanlp-core 쪽의 의존성 트리상에 scala-library 2.12.0 에 대한 의존성이 있는것으로 나왔습니다.
Spark의 경우 아직 scala 2.12를 지원하지 않는것으로 알고 있고 이에 따라 발생하는 이슈로 확인되었는데
scala 2.12를 완전히 회피 할 수 있는 방안이 있는지 궁금합니다.

**Comment by nearbydelta** [comment]
KoalaNLP는 cross-build를 통해서 scala 버전별로 패키지를 제공하고 있습니다.
때문에, koalanlp-core에서 문제가 발생한 것은 아닌 것 같습니다.

제가 짐작하건대, 해당 버전대에서 open-korean-text 분석기 버전을 `[1.2,)`와 같이 표기하여, 문제가 발생한 것 같습니다. 개발 당시에는 open-korean-text가 scala 버전을 변경하거나 큰 업그레이드를 하지 않을 것이라 보고 range 형태의 버전을 사용했었습니다. 이후에 open-korean-text가 scala를 2.12로 강제하면서 발생한 이슈입니다.

가능하시다면, sbt/maven의 설정에서 "org.openkoreantext" % "open-korean-text"의 버전을 1.2나 해당 버전대로 강제해주시면 2.11에서 사용이 가능할 것 같습니다. (OKT 1.2는 KoalaNLP 1.5.2 당시의 기준 버전입니다)

**Comment by nearbydelta** [comment]
open-korean-text 1.x버전대에서도 Scala 2.12를 사용중이라, Scala 2.11은 open-korean-text의 전신인 (구) twitter-korean-text v4.4.4를 사용하여 지원하도록 변경했습니다.
`KoalaNLP-twitter` 버전 `1.8.3`을 사용하시면 버전 충돌 문제가 없을 것입니다.
