### ISSUE TITLE
ECMAscript 또는 python 지원

### ISSUE THREAD

**Issue by IkhanRyu** [nearbydelta/KoalaNLP#2]
facebook chatbot같은 chatbot application 개발할 때 활용할 수 있으면 좋을거 같습니다.

**Comment by nearbydelta** [comment]
안녕하세요, IkhanRyu님, 
제가 현재 ECMAScript v6나 Python으로 이를 개발할 여력이 되지 않습니다.
가능하시다면, pull하시어 통합해주시는 건 어떠실지요?
