### ISSUE TITLE
소스코드를 컴파일하라는 게 어떻게 하는건지 잘 모르겠습니다.

### ISSUE THREAD

**Issue by Gomyul** [nearbydelta/KoalaNLP#3]
cmd창에서 java -jar KoreanAnalyzer-0.2.2.3-jar-with-dependencies.jar를 쳤더니

C:\Users\dev\Desktop\DEVELOPER\KoreanAnalyzer-master> java -jar KoreanAnalyzer-0
.2.2.3-jar-with-dependencies.jar
오류: 기본 클래스 kr.kaist.ir.drm.entail.extraction.PairExtract을(를) 찾거나 로
드할 수 없습니다.

이렇게 뜨네요... 컴파일을 어떻게 해야 하는건지 자세한 설명을 부탁드립니다...ㅠ

**Comment by nearbydelta** [comment]
KoreanAnalyzer 디렉터리 하위에서,
- Maven이 설치된 경우 : `mvn package` 또는 `mvn assembly`를 실행하시고,
- Gradle을 사용하실 경우: `./gradle build`를 실행하시면 됩니다.

0.2.2.3-jar-with-dependencies.jar 파일은 잘못 올라간 것 같으니, 시간 되는 대로 수정하겠습니다.

**Comment by nearbydelta** [comment]
소스코드 컴파일이 배포에 좋지 못한 듯 하여, Maven repository를 설정하였습니다.
관리의 편의를 위해서 Java에서 Scala로 코드를 변경하였습니다만,
Java에서도 거의 동일하게 사용할 수 있으므로, README를 한번 읽어보시고 사용하시면 될 것 같습니다.
